version: "3"

services: 
  label-studio:
    container_name: label-studio
    build: .
    working_dir: /label-studio
    volumes:
      - ./labeling_project:/label-studio/labeling_project
    command: "label-studio start labeling_project ${INIT_COMMAND} --host 0.0.0.0"
    ports:
      - "8080:8080"
    restart: always
